version: "2.4"

services:
  postgres-replica:
    build:
      context: ../docker/postgres-replica
    image: virak/pdns-postgres-replica:local
    container_name: pdns-postgres-replica
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data
      PRIMARY_HOST: ${PRIMARY_HOST}
      PRIMARY_PORT: ${PRIMARY_PORT}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_SLOT_NAME: ${REPLICATION_SLOT_NAME}
      REPLICA_CREATE_SLOT: ${REPLICA_CREATE_SLOT}
      REPLICATION_SSLMODE: ${REPLICATION_SSLMODE}
    ports:
      - "${POSTGRES_REPLICA_PORT}:5432"
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data
      - ./tls:/tls:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

volumes:
  postgres-replica-data:
